export const metadata = {
	title: 'Next js',
	description: 'Generated by Next.js',
}
export default function DocsLayout (
	{ children }: {children: React.ReactNode}) {
	return (
		<>
			{children}
			<h2>Test layout</h2>
		</>
	);
};
